# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jindan Huang
tagline:          'Jindan Huang'
description:      'Healthcare + Computer Science Lover'
url:              https://melody8282.github.io/

author:
  name:           'Jindan Huang'
  url:            https://melody8282.github.io/

paginate:         2

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/melody8282/

tags:

github_username:  melody8282


