# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jindan Huang
tagline:          'A Jekyll theme'
description:      'Healthcare + Computer Science Lover'
url:              http://hyde.getpoole.com
baseurl:          https://melody8282.github.io/hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
