# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jindan Huang
tagline:          'Jindan Huang'
description:      'Healthcare + Computer Science Lover'
url:              http://hyde.getpoole.com
baseurl:          https://melody8282.github.io/

author:
  name:           'Jindan Huang'
  url:            https://melody8282.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/melody8282/
